Repository hook-killer/front-end, pull requests merged in 2023-10, with the labels that each got.

#10 fix : 게시글 작성 기능 수정
  src/App.js
  src/components/article/add.jsx
Labels: bug

#16 [FEATURES] 메인페이지 기능구현
  package-lock.json
  src/App.js
  src/api/ArticleApi.jsx
  src/components/main/PopularBox.jsx
  src/components/test/test1.jsx
Labels: enhancement

#17 feat : 다국어 처리 기능 (미완성)
  package-lock.json
  package.json
  src/App.js
  src/components/article/add.jsx
  src/components/article/list.jsx
  src/components/common/Header.jsx
  src/i18n.js
  src/i18ntest.js
  src/locales/cn/translation.json
  src/locales/en/translation.json
  src/locales/jp/translation.json
  src/locales/ko/translation.json
Labels: enhancement

#18 feat: 검색창 연관검색어 구현, 검색결과 페이지네이션 구현중 #13
  .idea/.gitignore
  .idea/front-end.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/App.js
  src/api/SearchApi.jsx
  src/components/common/Header.jsx
  src/components/common/PaginationComponent.jsx
  src/components/search/RelatedSearches.jsx
  src/components/search/result.jsx
  src/components/search/searchBar.jsx
Labels: enhancement

#19 [FEATURE] mypage 구현 미완
  .gitignore
  src/App.js
  src/api/DefaultClient.jsx
  src/api/MypageApi.jsx
  src/components/mypage/MypageList.css
  src/components/mypage/MypageList.jsx
  src/components/mypage/UserInfoUpdateModal.jsx
  src/components/mypage/UserProfile.jsx
  src/components/mypage/UserThumbnail.jsx
  src/pages/Mypage.css
  src/pages/Mypage.jsx
Labels: enhancement

#23 [FEATURE] 검색 기능 구현 완료
  src/components/common/PaginationComponent.jsx
  src/components/search/result.jsx
  src/components/search/searchBar.jsx
  src/locales/cn/translation.json
  src/locales/en/translation.json
  src/locales/jp/translation.json
  src/locales/ko/translation.json
Labels: enhancement

#32 기능추가 및 리팩토링
  src/components/common/Header.jsx
  src/components/notice/add.jsx
  src/i18n.js
  src/locales/cn/translation.json
  src/locales/en/translation.json
  src/locales/jp/translation.json
  src/locales/ko/translation.json
Labels: enhancement, wontfix

#42 [FEATURE] Reply 관련 기능 구현
  src/App.js
  src/api/DefaultClient.jsx
  src/api/ReplyApi.jsx
  src/components/main/PopularBox.jsx
  src/components/reply/AlertDismissible.jsx
  src/components/reply/add.jsx
  src/components/reply/list.jsx
Labels: enhancement

#48 feat : 게시물 정보수정 구현 완료
  src/App.js
  src/api/ArticleApi.jsx
  src/api/MainCustomClient.jsx
  src/api/SearchCustomClient.jsx
  src/components/article/detail.jsx
  src/components/article/update.jsx
  src/components/common/Header.jsx
  src/components/mypage/UserInfoUpdateModal.jsx
  src/locales/cn/translation.json
  src/locales/en/translation.json
  src/locales/jp/translation.json
  src/locales/ko/translation.json
Labels: enhancement

#54 [FEATURE] 마이페이지 기능 구현
  package-lock.json
  package.json
  public/thumbnail.png
  src/App.js
  src/api/DefaultClient.jsx
  src/api/FileApi.jsx
  src/api/MypageApi.jsx
  src/components/common/Header.jsx
  src/components/mypage/MypageList.jsx
  src/components/mypage/UserInfoUpdateModal.jsx
  src/components/mypage/UserProfile.jsx
  src/components/mypage/UserThumbnail.jsx
  src/index.js
  src/locales/cn/translation.json
  src/locales/en/translation.json
  src/locales/jp/translation.json
  src/locales/ko/translation.json
  src/pages/Mypage.jsx
Labels: enhancement

#77 댓글 작성 이슈 해결, 댓글 삭제 이슈 발견하여 수정중
  src/api/ReplyApi.jsx
  src/components/article/detail.jsx
  src/components/reply/add.jsx
  src/components/reply/list.jsx
  src/components/search/RelatedSearches.jsx
  src/locales/cn/translation.json
  src/locales/en/translation.json
  src/locales/jp/translation.json
  src/locales/ko/translation.json
Labels: bug

#79 [FEATURE] 마이페이지 모달창 관련 이슈 수정
  src/components/mypage/MypageList.jsx
  src/components/mypage/UserInfoUpdateModal.jsx
Labels: enhancement

#101 fix : FE 썸네일 나올 수 있도록 추가 #93
  src/App.js
  src/components/auth/KakaoLogin.jsx
  src/components/auth/Login.jsx
  src/components/common/Header.jsx
  src/components/common/Profile.jsx
Labels: bug, wontfix

#102 fix : 헤더 닉네임 변경 이슈 #88
  src/App.js
  src/components/auth/GoogleLogin.jsx
  src/components/auth/KakaoLogin.jsx
  src/components/auth/Login.jsx
  src/components/mypage/UserInfoUpdateModal.jsx
  src/components/mypage/UserProfile.jsx
  src/pages/Mypage.jsx
  src/utils/ReactCookie.jsx
Labels: bug, wontfix

#108 feat : 댓글 작성자 프로필 썸네일 출력
  src/components/main/PopularBox.jsx
  src/components/reply/list.jsx
Labels: enhancement

#112 [FIX] 마이페이지 내 리스트 페이징처리 기능구현
  src/api/MypageApi.jsx
  src/components/article/detail.jsx
  src/components/mypage/MypageList.jsx
Labels: bug, wontfix

#109 feat : 게시물 작성자 사용자 정보 확인기능 추가
  src/components/article/detail.jsx
Labels: enhancement
